---
- name: Gather facts about EC2 instances
  hosts: localhost
  connection: local
  roles:
    - ec2

- name: Build the webapps
  hosts: webapps
  remote_user: ubuntu
  become: yes
  vars:
    pip_version: 9.0.1
    python_version: 3
    webapp_name: catordog
    db_user: ormuco
    db_password: ormuco17
    db_name: catordog
    db_host: catordogdb.cdyunxcavvb1.us-east-2.rds.amazonaws.com
    db_port: 5432
  roles:
    - flask
