---
- name: package update
  remote_user: root
  become: yes
  package:
    update_cache: "yes"
    cache_valid_time: 86400  # One day

- name: python3
  remote_user: root
  become: yes
  package: name={{item}} state=latest
  with_items:
    - python{{ python_version }}
    - python{{ python_version }}-pip
    - python{{ python_version }}-venv
    - ipython{{ python_version }}

- name: pip{{ python_version }} upgrade to {{ pip_version }}
  remote_user: root
  become: yes
  pip:
    name: pip
    executable: pip{{ python_version }}
    version: "{{ pip_version }}"

- name: Creates directory
  remote_user: root
  become: yes
  file:
    recurse: yes
    path: "/opt/{{ webapp_name}}"
    state: directory

- name: copy webapp code to /opt
  copy:
    src:  "{{ webapp_name }}"
    dest: /opt

- name: install venv
  remote_user: root
  become: yes
  pip:
    requirements: "/opt/{{ webapp_name }}/requirements.txt"
    virtualenv: "/opt/{{ webapp_name }}/venv"
    virtualenv_command: /usr/bin/python3 -m venv
  notify:
    - restart catordog

- name: install service
  remote_user: root
  become: yes
  template:
    src:  roles/flask/files/catordog.service.j2
    dest: /etc/systemd/system/catordog.service
  notify:
    - restart catordog

- name: started service
  remote_user: root
  become: yes
  service:
    name: catordog
    state: started

- name: Init db migration
  remote_user: root
  become: yes
  command: "python ./manage.py db init"
  environment:
    PATH: "/opt/{{ webapp_name }}/venv/bin"
  args:
    creates: "/opt/{{ webapp_name}}/migrations"
    chdir: "/opt/{{ webapp_name}}/"
  run_once: true

- name: Upgrade db schema
  remote_user: root
  become: yes
  command: "python ./manage.py db {{ item }}"
  args:
    chdir: "/opt/{{ webapp_name}}/"
  environment:
    PATH: "/opt/{{ webapp_name }}/venv/bin"
    DB_USER: "{{ db_user }}"
    DB_PASSWORD: "{{ db_password }}"
    DB_NAME: "{{ db_name }}"
    DB_HOST: "{{ db_host }}"
    DB_PORT: "{{ db_port}}"
  with_items:
    - migrate
    - upgrade
  run_once: true
